### ISSUE TITLE
[IndexError: tuple index out of range] nodes.py/627/return self.children[key]

### ISSUE THREAD

**Issue by KaKkouo** [KaKkouo/sphinxcontrib.kana_text#1]
この辺りが調べる箇所

```
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 633, in visit_kana
    self.body.append(node.ashtml())
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 502, in ashtml
    for isruby, value in self.asruby():
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 482, in asruby
    kana, word = self.askana(), self.asword()
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 440, in asword
    return self[self._1st].astext()
```

/tmp/sphinx-err-8tglg7i8.log

```
# Sphinx version: 4.2.0
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.1
# Last messages:
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
#   preparing documents...
#   done
#   writing output... [  1%] entry/_sheet
# Loaded extensions:
#   sphinx.ext.mathjax (4.2.0) from /usr/local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinxcontrib.embedding (0.6.1.dev1) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/embedding/__init__.py
#   sphinxcontrib.kana_text (0.21.0b12) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 357, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 531, in write
    self._write_serial(sorted(docnames))
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 541, in _write_serial
    self.write_doc(docname, doctree)
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/html/__init__.py", line 626, in write_doc
    self.docwriter.write(doctree, destination)
  File "/usr/local/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/local/lib/python3.8/site-packages/sphinx/writers/html.py", line 70, in translate
    self.document.walkabout(visitor)
  File "/usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "/usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 5 more times]
  File "/usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "/usr/local/lib/python3.8/site-packages/sphinx/util/docutils.py", line 477, in dispatch_visit
    method(node)
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 633, in visit_kana
    self.body.append(node.ashtml())
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 502, in ashtml
    for isruby, value in self.asruby():
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 482, in asruby
    kana, word = self.askana(), self.asword()
  File "/usr/local/lib/python3.8/site-packages/sphinxcontrib/kana_text/__init__.py", line 440, in asword
    return self[self._1st].astext()
  File "/usr/local/lib/python3.8/site-packages/docutils/nodes.py", line 627, in __getitem__
    return self.children[key]
IndexError: tuple index out of range
```

**Comment by KaKkouo** [comment]
解決。

表示用のクラスでElementクラスを継承していたのが、根本的な間違い。
これをTextクラスを継承する形に変えたら直った。

- エラーが出なくなったと思ったら肝心の用語が表示されなくなっていたりと、色々紆余曲折していた。
- TextElementは初期化時に文字列をTextクラスで代入し直すので使えない。
